--- #YAML:1.0
name:               Text-Scigen
version:            0.02
abstract:           Generate convincing-looking scientific articles
author:
    - Tim Brody <tdb2@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Text::Autoformat:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
